### ISSUE TITLE
Loading and rendering templates synchronously

### ISSUE THREAD

**Issue by slolo2000** [S2-/ejs-render-remote#1]
Hello,

I would like to know if you could add some functions to your plug-in:
- The first one which load a template synchronously and return the rendering
- The second one which simply load a template synchronously (without rendering) and return the ejs object (which could be rendered later)
- The third one which get ejs template in parameter and do the rendering (should be used after the second one)

The aim is to have two ways for using EJS, asynchronously and synchronously.

Do you think it could be a good idea?

Thanks in advance for your answer and have a nice day.

**Comment by 5im-0n** [comment]
Hi @slolo2000,

it's not possible to load the template synchronously because[ sync xmlhttprequest is deprecated](https://stackoverflow.com/questions/30876093/will-chrome-and-other-browsers-drop-support-for-synchronous-xmlhttprequest), and fetch is only async. But you can
```
ejs.preloadTemplate('template.ejs').then(function(t) {
  someDomelement.outerHTML = ejs.rr(t, {name: 'Simon'});
});
```
to get a very similar behaviour.

Does this help?

**Comment by slolo2000** [comment]
Thanks for your answer.

Sync request is always possible with ajax (see https://api.jquery.com/jquery.ajax/ and async setting)
I know that it is not the recommended way to work, but the software I used is coded with sync request for the moment and I don't have the choice for the moment.

Let me know if you are interested anyway for adding this functionality.

Have a nice day.

**Comment by 5im-0n** [comment]
Hi @slolo2000, how would you like your code to look like? Can you explain a bit better how this would work?
What are you doing now, and how would it look like with ejs.rr?

**Comment by slolo2000** [comment]
I am actually use an old plugin named embeddedjs which is a simple implementation of current ejs.co plugin.
By default, this plugin is able to load templates remotely (that is why I use it for now) and it loads them synchronously.

You can find the source code of embeddedjs here: https://pastebin.com/GZsrnHJX

So, here is how I use for now:

```
// Library for using EJS
var libEJS = (function() {
	var self = {};
	
	// Load a template remotely in order to render it later
	self.loadTpl = function(options) {
		var tpl = "";
		options = (typeof options === "undefined") ? {} : options;

		if (!("url" in options)) {
			return tpl;
		}
		tpl = new EJS(options);
		return tpl;
	};

	// Load a template remotely and render it directly if "url" is defined in options
	// Render a preloaded template if "tpl" is defined in options
	self.renderTpl = function(options, context) {
		var tpl = "";
		options = (typeof options === "undefined") ? {} : options;
		context = (typeof context === "undefined") ? {} : context;

		if ("url" in options) {
			tpl = new EJS(options).render(context);
		} else if ("tpl" in options) {
			tpl = options.tpl.render(context);
		}
		return tpl;
	};
})();


// Two examples using EJS

var objVar = {"a" : 1, "b" : "test"};

// Load template and render it directly
var html = libEJS.renderTpl({"url" : "tpl/test.ejs"}, objVar);
$("#id").html(html);


// Load template and render it later (for multiple uses for example)
htmlTpl  = libEJS.loadTpl({"url" : "templates/test.ejs"});

var html = "";
for (var i = 0; i < 10; i++) {
	objVar.a = i;
	objVar.b = "test: " + i;
	
	html += libEJS.renderTpl({"tpl": htmlTpl}, objVar);
}
$("#id").html(html);

///////////////////////////////////////////////////////
// What I expect with ejs-render-remote plugin

var objVar = {"a" : 1, "b" : "test"};

// Load template and render it directly (synchronously)
var html = ejs.srr("tpl/test.ejs"}, objVar);	// ssr for sync-render-remote
$("#id").html(html);


// Load template and render it later (for multiple uses for example)
htmlTpl  = ejs.slr({"url" : "templates/test.ejs"});	// slr for sync-loading-remote

var html = "";
for (var i = 0; i < 10; i++) {
	objVar.a = i;
	objVar.b = "test: " + i;
	
	html += ejs.rlt(objVar);	// rlt for render-loading-template
}
$("#id").html(html);
```

Do you see what I mean?

**Comment by 5im-0n** [comment]
Hi @slolo2000,

you can do this:
```
///////////////////////////////////////////////////////
// What I expect with ejs-render-remote plugin

var objVar = {"a" : 1, "b" : "test"};

// Load template and render it directly (synchronously)
var html = ejs.srr("tpl/test.ejs", objVar);	// ssr for sync-render-remote
$("#id").html(html);

// currently possible syntax that does the same:
ejs.preloadTemplate('tpl/test.ejs').then(function(t) {
  var html = ejs.rr(t, objVar);
  $("#id").html(html);
});


// Load template and render it later (for multiple uses for example)
htmlTpl  = ejs.slr({"url" : "templates/test.ejs"});	// slr for sync-loading-remote

var html = "";
for (var i = 0; i < 10; i++) {
  objVar.a = i;
  objVar.b = "test: " + i;

  html += ejs.rlt(objVar);	// rlt for render-loading-template
}
$("#id").html(html);


// currently possible syntax that does the same:
ejs.preloadTemplate('templates/test.ejs').then(function(t) {
  var html = "";
  for (var i = 0; i < 10; i++) {
    objVar.a = i;
    objVar.b = "test: " + i;

    html += ejs.rr(t, objVar);
  }

  $("#id").html(html);
});
```

**Comment by slolo2000** [comment]
You are right, it is a possible syntax, but you are still asynchronous with this way.

What I would like ideally is not to have to modify too much my code because it is a rather big project and the current way to load template force me to rewrite a lot of pieces of my source code (synchronous source code is quite different than asynchronous code to write)

So, I will rewrite my code later for better performance but it will take some time and for now I think is easier to adjust the way you use your plugin than rewrite a lot of pieces of code.

But I can understand it make no sense to add such new methods into your plugin. I can write my own plugin but I thought it could be interesting for people to have another way to render remote template from client side with ejs into a single plugin.

**Comment by 5im-0n** [comment]
Hi @slolo2000, I don't want to add a sync method to the plugin because it would trigger a warning in the console, and it's not something I would like to introduce in the plugin.
But you could archive the same effect by preloading all your templates with something like
```
ejs.preloadTemplate('template1.ejs');
ejs.preloadTemplate('template2.ejs');
ejs.preloadTemplate('template3.ejs');
...
```
in your js code. After you preloaded all templates, `ejs.rr` will be synchronous everywhere you use it.

**Comment by slolo2000** [comment]
Thanks for your answer.

This warning is due to console options but I respect your choice.
I will try to see what is the best to do for my project.

Thanks for the time you gave me and I hope your plugin will be a part of ejs in the future.

Have a nice day.
